name: Deploy to Hostinger
on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Cache para pnpm
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Check if lock file exists
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "✅ pnpm-lock.yaml encontrado"
            ls -la pnpm-lock.yaml
          else
            echo "❌ pnpm-lock.yaml no encontrado"
            echo "Archivos en directorio raíz:"
            ls -la
          fi

      - name: Install dependencies
        run: |
          # Si tienes pnpm-lock.yaml, usa pnpm install --frozen-lockfile
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install --frozen-lockfile
          else
            # Si no tienes lock file, usa pnpm install
            pnpm install
          fi

      - name: Build Astro project
        run: |
          pnpm run build
          # Verificar que el build se completó
          ls -la dist/

      - name: Optimize build output
        run: |
          # Crear directorio para archivos optimizados
          mkdir -p optimized_build
          
          # Copiar archivos del build
          cp -r dist/* optimized_build/
          
          # Copiar archivos de configuración del servidor (si existen)
          if [ -f "public/.htaccess" ]; then
            cp public/.htaccess optimized_build/
            echo "✅ .htaccess copiado"
          fi
          
          if [ -f "public/robots.txt" ]; then
            cp public/robots.txt optimized_build/
            echo "✅ robots.txt copiado"
          fi
          
          # Verificar estructura
          echo "Estructura del build optimizado:"
          find optimized_build -type f | head -20

      - name: Deploy to Hostinger via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          source: "optimized_build/*"
          target: "public_html/"
          rm: true
          strip_components: 1
          overwrite: true

      - name: Verify deployment
        run: |
          echo "✅ Deploy completado exitosamente a Hostinger"
          echo "🌐 Sitio desplegado"
          echo "📁 Archivos desplegados en: public_html/"

      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Limpiando archivos temporales..."
          rm -rf optimized_build/
          rm -rf dist/